### ISSUE TITLE
Option to disable GPG usage

### ISSUE THREAD

**Issue by vitalyster** [Gonzih/feeds2imap.clj#9]
I have set up feeds2imap as cron job on remote VPS, in this case I think encrypting imap settings is meaningless: I need to expose my key passphrase in plain text, which is the same as store imap settings unencrypted. 
The only problem is - I want to see cron alerts when some error happened, but it spams me on every feeds2imap launch because gpg errors are on stderr. Is it possible to add an option to skip reading encrypted imap settings?

**Comment by Gonzih** [comment]
It will read encrypted setting only if encrypted file exists.



—
Regards,
Max

**Comment by vitalyster** [comment]
Then it is broken:
```
$ ls ~/.config/feeds2imap.clj/
imap.clj  read-items.clj  urls.clj
[vt@my ~]$ ~/bin/lein feeds2imap pull
Could not decrypt credentials from /home/vt/.config/feeds2imap.clj/imap.clj.gpg
gpg: can't open `/home/vt/.config/feeds2imap.clj/imap.clj.gpg'
gpg: decrypt_message failed: file open error
```
